[tool.poetry]
name = "sknlp"
version = "0.1.0"
description = ""
authors = ["nanaya <nanaya100@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
sklearn = "^0.0"
tabulate = "^0.8.6"
pandas = "^0.25.3"
joblib = "^0.14.1"
jieba_fast = "^0.53"
tf-estimator-nightly = "^2.1.0-alpha.2020030401"
tf-nightly = "^2.2.0-alpha.20200304"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
